### PR TITLE
Removed useless comment

### PR DESCRIPTION
**Pull request by Cube9999**
I am very useful

### CODE REVIEW

**Comment by viown** [comment]
I placed that comment for no reason, but it was completely intentional!

**Comment by viown** [comment]
whatever I'll merge anyways

**Comment by Cube9999** [comment]
This is a really harmful bug that makes the whole project vulnerable, thanks for merging

**Comment by viown** [comment]
you're a prick

**Comment by Cube9999** [comment]
you're a dangling pointer

**Comment by viown** [comment]
how dare you

**Comment by Cube9999** [comment]
haha

**Comment by viown** [comment]
don't make me say the S word

**Comment by viown** [comment]
sid

**Comment by Cube9999** [comment]
you're a DWORD

**Comment by Cube9999** [comment]
> sid

Reporting to github!

**Comment by viown** [comment]
oh no!

**Pull request merged**
